---
- name: Base packages - ToDo Refactor
  hosts: all
  connection: local

  tasks:
  - name: Install swap
    become: yes
    apt:
        name: dphys-swapfile
        update_cache: yes
        cache_valid_time: 3600
    notify:
        - dphys-swapfile

  - name: Configure swap
    become: yes
    lineinfile:
        regexp: "^CONF_SWAPSIZE=*"
        line: "CONF_SWAPSIZE=1024"
        path: /etc/dphys-swapfile
        state: present
    register: dphys
    notify:
        - dphy-swapfile

  - name: Ensure swap file is 1GiB
    stat:
        path: /var/swap
    register: swap_file
    #when_change: False
    
  - name: Ensure dphys is not running
    become: yes
    service:
        name: dphys-swapfile
        state: stopped
    when: dphys is changed or not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphy-swapfile

  - name: Ensure swap-file exists
    become: yes
    command: dd if=/dev/zero of=/var/swap count=1024 bs=1MiB
    when: not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphy-swapfile

  - name: Make swap
    become: yes
    command: mkswap /var/swap
    when: not swap_file.stat.exists or swap_file.stat.size!=1073741824
    notify:
        - dphy-swapfile

  - name: Flush handlers
    meta: flush_handlers

  - name: Remove realvnc-vnc-server
    become: yes
    apt:
      name:
        - realvnc-vnc-server
      state: absent
    register: realvnc_vnc_server
  - name: Remove realvnc-vnc-server as a service
    become: yes
    service:
      name: vncserver-x11-serviced
      state: stopped
      enabled: no
    when: realvnc_vnc_server is changed

  - name: Add RDP
    become: yes
    apt:
      name:
        - xrdp
      update_cache: yes
      cache_valid_time: 3600
    # ToDo into Jupyternotebook??

  - name: Ensure jupyter dependencies are installed
    become: yes
    apt:
        name:
          - libxml2-dev
          - libxslt1-dev

  - name: Ensure dependencies are installed
    become: yes
    apt:
        name:
          - avahi-utils
          - avahi-daemon
          - acl
          - build-essential
          - curl
          - cowsay
          - debian-keyring
          - debian-archive-keyring
          - dphys-swapfile
          - expect
          - git
          - ieee-data
          - libffi-dev
          - libssl-dev
          - lsof
          - nmap
          - python-rpi.gpio
          - python3-rpi.gpio
          - python-pexpect
          - python-dev
          - python3-dev
          - python3-pip
          - rsync
          - sudo
          - sl
          - sshpass
          - screen
          - tree
          - tidy
          - vim
          - zip
          # ToDo Jave could not installed because certificates are wrong
          #- lsb-core
          #- openjdk-9-jdk
          #- oracle-java8-jdk
        update_cache: yes
        cache_valid_time: 3600
    tags:
        - base

  - name: Ensure raspians dependencies are installed
    become: yes
    apt:
        name:
          - python3-matplotlib
          - python-matplotlib
        update_cache: yes
        cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"
    tags:
        - base

  - name: Ensure raspians dependencies are installed
    become: yes
    apt:
        name:
          - libjpeg62-turbo
          - libjpeg62-turbo-dev
          - raspi-gpio
          - sense-hat
          - wiringpi
        update_cache: yes
        cache_valid_time: 3600
    when: ansible_distribution != "Ubuntu"
    tags:
        - base

  - block:
    - name: Ensure raspberry dependencies are installed
      become: yes
      apt:
          name:
            - oracle-java8-jdk
            - openjdk-9-jdk
    - name: Alternatives set
      become: yes
      alternatives:
          path: /usr/lib/jvm/java-9-openjdk-armhf/bin/java
          name: java
      tags:
          - base
    when: ansible_architecture == "never"

  - name: Ensure python packages are installed
    become: yes
    pip:
      name:
        - paho-mqtt
        - tweepy
        - psutil
        #ToDo remove into jupyter role
        - six
      executable: pip3
      state: present

  - name: Git config
    git_config:
        name: "{{item.name}}"
        value: "{{item.value}}"
        scope: global
    with_items:
        - name: "user.email"
          value: "{{ansible_user_id}}@example.com"
        - name: "user.name"
          value: "{{ansible_user_id}}"
        - name: "core.editor"
          value: "vim"
        - name: "push.default"
          value: "current"
    tags:
        - git

  handlers:
  - name: dphy-swapfile
    become: yes
    service:
        name: dphys-swapfile
        state: restarted
        enabled: yes

- name: Base packages for pi3 only - ToDo Refactor
  hosts: pis
  connection: local

  tasks:
  # ToDo Remove from base
  - name: Ensure mqtt is installed
    become: yes
    apt:
        name:
          - mosquitto
          - mosquitto-clients
        update_cache: yes
        cache_valid_time: 3600
    tags:
        - mqtt
