---
- name: Base packages - ToDo Refactor
  hosts: all
  connection: local

  tasks:
  - name: Ensure jupyter dependencies for armv6l are installed
    become: yes
    apt:
        name:
          - libxml2-dev
          - libxslt1-dev
    when: ansible_architecture == "armv6l"
  - name: Ensure raspberry dependencies are installed
    become: yes
    apt:
        name:
          - git
          - nmap
          - curl
          - sudo
          - expect
          - sense-hat
          - raspi-gpio
          - python-rpi.gpio
          - python3-rpi.gpio
          #- python3-blinkt
          #- python-blinkt
          - debian-keyring
          - debian-archive-keyring
          - wiringpi
          - lsb-core
          - avahi-utils
          - avahi-daemon
          #- openjdk-9-jdk
          #- oracle-java8-jdk
          - tidy
          - python-pexpect
          - sl
          - libjpeg62-turbo
          - libjpeg62-turbo-dev
          # Not in Ubuntu 1604
          #- liblcms1-dev
          #- liblcms1

        update_cache: yes
        cache_valid_time: 3600
    tags:
        - base
  - block:
    - name: Ensure raspberry dependencies are installed
      become: yes
      apt:
          name:
            - oracle-java8-jdk
            - openjdk-9-jdk
    - name: Alternatives set
      become: yes
      alternatives:
          path: /usr/lib/jvm/java-9-openjdk-armhf/bin/java
          name: java
      tags:
          - base
    when: ansible_architecture != "armv6l"

  - name: Ensure python packages are installed
    become: yes
    pip:
      name:
        - paho-mqtt
        - tweepy
        - psutil
      executable: pip3
      state: present # The state of module,The 'forcereinstall' option is only available in Ansible 2.1 and above.

  - name: Ensure Jupyter and some kernel/extensions are installed
    become: yes
    pip:
      name: "{{items}}"
      executable: pip3
      state: forcereinstall
    with_items:
      - six
    when: ansible_architecture == "armv6l"

  - name: Git config
    git_config:
        name: "{{item.name}}"
        value: "{{item.value}}"
        scope: global
    with_items:
        - name: "user.email"
          value: "{{ansible_user_id}}@example.com"
        - name: "user.name"
          value: "{{ansible_user_id}}"
        - name: "core.editor"
          value: "vim"
        - name: "push.default"
          value: "current"
    tags:
        - git

- name: Base packages for pi3 only - ToDo Refactor
  hosts: pi3
  connection: local

  tasks:
  # ToDo Remove from base
  - name: Ensure mqtt is installed
    become: yes
    apt:
        name:
          - mosquitto
          - mosquitto-clients
        update_cache: yes
        cache_valid_time: 3600
    tags:
        - mqtt
