---
- hosts: all

  vars:
  - db_user:
        name: "example_user"
        password: "passw0rd"
  - phpmyadmin_version: "4.8.3"

  roles:
  - role: geerlingguy.mysql
    become: yes
    mysql_root_home: /root
    mysql_user_name: root
    mysql_user_password: root
    mysql_root_password_update: yes
    mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
    mysql_users:
    - name: "{{db_user.name}}"
      host: "%"
      password: "{{db_user.password}}"
      priv: "example_db.*:ALL"
    - name: admin
      host: "127.0.0.1"
      password: "admin"
      priv: "*.*:ALL"
    tags:
      - db_mysql

  pre_tasks:
  - name: Debug info
    debug:
        msg: "USER_ID is {{ansible_user_id}} and Home is {{ansible_user_dir}}"
        verbosity: 1

  tasks:
  - name: Ensure sqlite3 is installed
    become: yes
    apt:
        name: sqlite3
        update_cache: yes
        cache_valid_time: 3600

  - name: Ensure PHP ist installed
    become: yes
    apt:
        name:
          - nginx-full
          - php
          - php-curl
          - php-gd
          - php-fpm
          - php-cli
          - php-opcache
          - php-mbstring
          - php-xml
          - php-zip
          - php-mysql
          - libmcrypt4
          - php-pear
          - php-ssh2
          - php-mcrypt
        update_cache: yes
        cache_valid_time: 3600

  - name: Default nginx config
    become: yes
    template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: "{{item.owner | default('root')}}"
        group: "{{item.group | default('root')}}"
    with_items:
        - src: default.j2
          dest: /etc/nginx/sites-available/default
        - src: php7_common.j2
          dest: /etc/nginx/php7_common
    notify:
        - restart_nginx
        - restart_php-fpm

  - name: Ensure /var/www owned by www-data
    become: yes
    file:
        path: /var/www
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
    tags:
        - php
        - nginx

  - name: Ensure {{ansible_user_id}} is in group www-data
    become: yes
    user:
        name: "{{item}}"
        groups: www-data
        append: yes
    with_items:
        - "{{ansible_user_id}}"
    tags:
        - php
        - nginx

  - name: Ensure www-data is in group gpio
    become: yes
    user:
        name: "{{item}}"
        groups: gpio
        append: yes
    with_items:
        - www-data
    tags:
        - php
        - nginx

  - name: Ensure www directory for {{ansible_user_id}} exists
    file:
        path: "{{ansible_user_dir}}/www"
        state: directory
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
    tags:
        - php
        - nginx

  - name: Ensure some html for {{ansible_user_id}} exists
    template:
        src: "{{item}}.j2"
        dest: "{{ansible_user_dir}}/www/{{item}}"
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"
    with_items:
        - index.html
        - index.php
    tags:
        - php
        - nginx

  - name: Ensure /var/www/html/phpMyAdmin is directory
    become: yes
    file:
        path: /var/www/html/phpMyAdmin
        state: directory
        owner: www-data
        group: www-data
    tags:
        - phpmyadmin

  - name: Ensure phpmyadmin ist installed
    become: yes
    unarchive:
        dest: /var/www/html/phpMyAdmin
        src: https://files.phpmyadmin.net/phpMyAdmin/{{phpmyadmin_version}}/phpMyAdmin-{{phpmyadmin_version}}-all-languages.tar.gz
        extra_opts: --strip-components=1
        creates: /var/www/html/phpMyAdmin/LICENSE
        group: www-data
        owner: www-data
        remote_src: yes
    tags:
        - phpmyadmin

  - name: Ensure phpmyadmin config is installed
    become: yes
    template:
        src: config.inc.php.j2
        dest: /var/www/html/phpMyAdmin/config.inc.php
        owner: www-data
        group: www-data
    tags:
        - phpmyadmin

  - name: Ensure mongodb is installed
    become: yes
    apt:
        name: mongodb-server
        update_cache: yes
        cache_valid_time: 3600
    tags:
        - mongodb

  handlers:
  - name: restart_nginx
    become: yes
    service:
      enabled: yes
      state: restarted
      name: nginx

  - name: restart_php-fpm
    become: yes
    service:
      enabled: yes
      state: restarted
      name: php-fpm
