---
- name: Install inspec on pi
  hosts: pi3
  connection: local

  tasks:
  #- name: Run old inspec script
  #  script: install_inspec.sh

  - name: Install inspec dependencies
    become: yes
    apt:
      name:
        - ruby
        - ruby-dev
        - gem
        - xvfb
        - firefox-esr
        - libfontconfig1
        - libfreetype6
        #ToDo inspec could not installed in buster
        #- libicu63
        - libssl1.0.2
        - fontconfig
        - zlib1g-dev
        - zlib1g
        - python3-pip
        - phantomjs
      update_cache: yes
      cache_valid_time: 3600

  - name: Install gems
    become: yes
    gem:
      name: "{{item}}"
      user_install: no
    with_items:
      #ToDo inspec could not installed in buster
      #- inspec
      - bundler

  - name: Install inspec for armv7l
    become: yes
    gem:
      name: "{{item.name}}"
      version: "{{item.version}}"
      user_install: no
    with_items:
      #ToDo inspec could not installed in buster
      - name: inspec
        version: 1.51.25

  - name: Install capybara-edu-devops
    bundler:
      state: present # The desired state of the Gem bundle. C(latest) updates gems to the most recent, acceptable version
      gemfile: Gemfile
      user_install: yes # Only applies if state is C(present). Installs gems in the local user's cache or for all users
      chdir: capybara-edu-devops

  #- name: Install phantomjs
  #  become: yes
  #  get_url:
  #    url: https://github.com/piksel/phantomjs-raspberrypi/raw/stretch/bin/phantomjs
  #    dest: /usr/local/bin/phantomjs
  #    owner: root
  #    group: root
  #    mode: 0755

  - name: Get geckodriver
    become: yes
    unarchive:
      src: https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-arm7hf.tar.gz
      dest: /usr/local/bin/
      remote_src: yes

  - name: Get selenium
    become: yes
    pip:
      name:
        - selenium
        - pyvirtualdisplay
      executable: pip3
