---
- name: Install Jupyter
  hosts: all
  connection: local
  vars:
    - nodejs_minor_version: "10"

  roles:
  - role: kraeml.jupyter
    become: yes
    tags: jupyter
    nodejs_version: "{{nodejs_minor_version}}.x"
    npm_config_unsafe_perm: "true"

  pre_tasks:
  - name: Debug info
    debug:
        msg: "USER_ID is {{ansible_user_id}} and Home is {{ansible_user_dir}}"
        #verbosity: # A number that controls when the debug is run, if you set
        # to 3 it will only run debug when -vvv or above
  - name: Get nodejs info
    shell: nodejs --version | cut -d '.' -f 1 | tr -d 'v'
    ignore_errors: yes
    register: nodejs_pi_version
    changed_when: false

  - name: Output nodejs Version
    debug:
        var: nodejs_pi_version
        verbosity: 1

  - name: Install nodejs
    block:
      - name: Shell script nodejs
        shell: curl -sL https://deb.nodesource.com/setup_{{nodejs_minor_version}}.x | sudo -E bash - 2>&1 | sudo tee -a /var/log/node-install.log >>/dev/null
        when: ansible_architecture != "armv6l"

      - name: Shell script nodejs armv6l
        shell: wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh | bash
        when: ansible_architecture == "armv6l"

      - name: Ensure nodejs as link exists
        become: yes
        file:
          src: /opt/nodejs/bin/node
          dest: "{{item}}/nodejs"
          state: link
        with_items:
          - /usr/bin
          - /usr/sbin
          - /sbin
          - /usr/local/bin
          - /opt/nodejs/bin
        when: ansible_architecture == "armv6l"

      - name: Install nodejs in minor version
        become: yes
        apt:
          force: yes
          name: "nodejs={{nodejs_minor_version_number}}.*"
          update_cache: yes
          cache_valid_time: 3600
        when: ansible_architecture != "armv6l"

      - name: NPM unsafe-perm
        become: yes
        become_method: sudo
        become_flags: "-H"
        command: npm config --global set unsafe-perm=true
    when: nodejs_pi_version.stdout != nodejs_minor_version_number

  tasks:
  - name: Ensure link to rdf-edu-notbooks exitst
    file:
      src: "{{ansible_user_dir}}/.raspberry-edu-devops/notebooks"
      dest: "{{ansible_user_dir}}/notebooks/raspberry-edu-devops"
      state: link
