---
- name: Install LXC
  hosts: pis
  connection: local

  tasks:
  - name: install LXC
    become: yes
    apt:
      name:
        - lxc
        - lxctl
        - xz-utils
        - bridge-utils
        - dnsmasq-base
        - iptables
        - debootstrap

  - name: Modeprobe
    become: yes
    command: modprobe configs

  - name: LXC Test
    become: yes
    command: lxc-checkconfig

  - name: LXC Config
    become: yes
    template:
      src: "{{item}}.j2"
      dest: "/{{item}}"
    notify:
      - lxc_restart
    with_items:
      - "etc/lxc/default.conf"
      - "etc/default/lxc-net"

  handlers:
  - name: lxc_restart
    become: yes
    service:
      name: lxc-net
      state: restarted
