---
- name: Romi chasis setup
  hosts: piromi
  connection: local

#https://www.pololu.com/blog/663/building-a-raspberry-pi-robot-with-the-romi-chassis

  tasks:
  - debug:
      var: ansible_user
      verbosity: 1
  - name: Install flask
    apt:
      name:
        - python3
        - python3-flask
        - python3-smbus

  - name: Get i2c
    become: yes
    command: raspi-config nonint get_i2c
    register: i2c_setings

  - name: Debug i2c_setings
    debug:
      var: i2c_setings
      verbosity: 1

  - name: Set i2c
    become: yes
    command: raspi-config nonint do_i2c 0
    when: i2c_setings.stdout == "1"

  # wget https://github.com/pololu/pololu-rpi-slave-arduino-library/archive/<version>.tar.gz
  # tar -xzf <version>.tar.gz
  # mv pololu-rpi-slave-arduino-library-master pololu-rpi-slave-arduino-library
  # - name: Download https://codeload.github.com/pololu/pololu-rpi-slave-arduino-library/tar.gz/2.0.0
  - name: download the pololu-rpi-slave-arduino-library code
    git:
      dest: "{{ansible_user_dir}}/pololu-rpi-slave-arduino-library"
      repo: https://github.com/pololu/pololu-rpi-slave-arduino-library.git

  - name: Start the server automatically
    become: yes
    template:
      dest: "/lib/systemd/system/{{item}}.service"
      src: "lib/systemd/system/{{item}}.service.j2"
    register: "a_star_restart"
    with_items:
      - a_star_slave
      - a_star_heartbeat

  handlers:
    - name: a_star_restart
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      with_items:
        - a_star_heartbeat
        - a_star_slave
...
