---
- hosts: all

  roles:
  - role: jupyter
    become: yes
  - role: geerlingguy.docker
    become: yes
    docker_apt_release_channel: stable
    docker_apt_repository: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_install_compose: false
    docker_compose_version: "1.16.1"
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
  - name: Ensure user pi is member of group docker
    become: yes
    user:
        name: pi
        generate_ssh_key: yes
        ssh_key_type: rsa
        groups: docker
        append: yes

  - name: Ensure raspberry dependencies are installed
    become: yes
    apt:
        name: "{{item}}"
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes
    with_items:
        - nmap
        - curl
        - sudo
        - expect
        - sense-hat
        - raspi-gpio
        - debian-keyring
        - debian-archive-keyring
        - wiringpi
        - raspi-gpio
        - dphys-swapfile
        - lsb-core
        - avahi-utils
        - avahi-daemon
        - openjdk-8-jre
        - tidy

  - name: Alternatives set
    become: yes
    alternatives:
        path: /usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java
        name: java

  - name: Pip3 dependencies
    become: yes
    pip:
        name: html5validator
        executable: pip3
        state: present

  - name: Ensure tex dependencies are installed
    become: yes
    apt:
        name: "{{item}}"
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes
    with_items:
        - texlive
        - texlive-latex-extra
        - dvipng
        - texlive-xetex
        - texlive-latex-recommended
        - texlive-fonts-recommended

  - name: Ensure nodred and some dependencies are installed
    become: yes
    npm:
        name: "{{item}}"
        global: yes
    with_items:
        - node-red
        - node-red-node-random
        - node-red-node-ping
        - node-red-node-smooth
        #- node-red-contrib-ibm-watson-iot
        - node-red-contrib-play-audio
        #- node-red-node-ledborg
        - node-red-node-pi-sense-hat
        #- node-red-node-serialport
        - npm-check
        - node-red-admin

  - name: add the shortcut and start/stop/log scripts
    become: yes
    get_url:
        dest: "{{item.des}}"
        url: "{{item.url}}"
        mode: 0755
    with_items:
        - des: /usr/bin/node-red-start
          url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-start2
        - des: /usr/bin/node-red-stop
          url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-stop
        - des: /usr/bin/node-red-log
          url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-log

  - name: add systemd script and configure it for $USER
    become: yes
    get_url:
        dest: /lib/systemd/system/nodered.service
        url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/nodered.service
    notify: restart_nodred

  - name: Flush handlers
    meta: flush_handlers

  - name: Install node-red addons
    npm:
        name: "{{item}}"
        state: present
        path: /home/pi/.node-red
    with_items:
        - node-red-dashboard
        - node-red-contrib-bigtimer
        - node-red-node-mongodb
        - node-red-node-mysql
        - node-red-contrib-looptimer

  - name: Ensure sqlite3 is installed
    become: yes
    apt:
        name: "{{item}}"
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes
    with_items:
        - sqlite3

  - name: Additional packages for web-dev learning
    become: yes
    npm:
        name: "{{item}}"
        state: present
        global: yes
    with_items:
        - pm2
        - socket.io
        - sqlite3
        - mongoose
        - mysql
        - express
        - javascripting
        - how-to-npm
        - scope-chains-closures
        - stream-adventure
        - how-to-markdown
        - learnyouhtml
        - learnyounode
        - functional-javascript-workshop
        - bytewiser
        - expressworks
        - bug-clinic
        - async-you
        - test-anything
        - learnyoumongo
        - torrential
        - html-validator-cli

  - name: Ensure cloud9 dependencies are installed
    apt:
        name: tmux
        update_cache: yes
        cache_valid_time: 3600
        install_recommends: yes

  - name: Clone cloud9
    git:
        dest: /home/pi/cloud9
        repo: https://github.com/c9/core.git
        clone: yes
        update: yes
    register: clone_cloud9

  - name: Install cloud9
    script: /home/pi/cloud9/scripts/install-sdk.sh
    args:
        chdir: /home/pi/cloud9/
    when: clone_cloud9.changed
    notify:
        - restart_cloud9

  - name: Install cloud9 systemd scripts
    template:
        src: cloud9.service.j2
        dest: /lib/systemd/system/cloud9.service
        mode: 0644
    notify:
        - restart_cloud9

  handlers:
  - name: restart_nodred
    become: yes
    service:
      enabled: yes
      state: restarted
      name: nodered.service

  - name: restart_cloud9
    become: yes
    service:
      enabled: yes
      state: restarted
      name: cloud9.service
