---
- name: Setup the pi for ansible playbooks
  hosts: pi3
  connection: local
  gather_facts: no

  tasks:
    - name: Some output
      debug:
        verbosity: 1

    - name: Ensure global ansible dir exists
      become: yes
      file:
        path: /etc/ansible/roles
        state: directory

    - name: Ensure global ansible inventory exists
      become: yes
      template:
        dest: "/etc/ansible/{{item}}"
        src: "{{item}}.j2"
      with_items:
        - "hosts"

    - name: Ensure global ansible inventory exists workaround no loop
      become: yes
      copy:
        dest: "/etc/ansible/ansible.cfg"
        src: "ansible.cfg.j2"

- import_playbook: pi-inspec.yml
- import_playbook: pi-nodered.yml
- import_playbook: pi-jupyter.yml
- import_playbook: pi-databases.yml
- import_playbook: pi-cloud9.yml
- import_playbook: pi-etherwrite.yml
- import_playbook: pi-tex.yml
- import_playbook: pi-web-dev.yml
# ToDo Refactor next playbook
- import_playbook: pi-base.yml
