---
# ToDo Refactor next playbook
- import_playbook: pi-base.yml

- name: Setup the pi for ansible playbooks
  hosts: all
  connection: local
  gather_facts: no
  # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Some output
      debug:
        verbosity: 1

    - name: Ensure global ansible dir exists
      become: yes
      file:
        path: /etc/ansible/roles
        state: directory

    - name: Ensure global ansible inventory exists
      become: yes
      template:
        dest: "/etc/ansible/{{item}}"
        src: "{{item}}.j2"
      with_items:
        - "hosts"
        - "ansible.cfg"

- import_playbook: pi-inspec.yml
#ToDo Ubuntu core testing below
- import_playbook: pi-nodered.yml
- import_playbook: pi-jupyter.yml
- import_playbook: pi-databases.yml
- import_playbook: pi-cloud9.yml
- import_playbook: pi-etherwrite.yml
- import_playbook: pi-tex.yml
- import_playbook: pi-web-dev.yml
- import_playbook: pi-romi.yml
- import_playbook: pi-lxc.yml
- import_playbook: ubuntu-romi.yml
#- import_playbook: pi-roberta.yml
- import_playbook: pi-argon.yml
