---
- name: Setup the pi for ansible playbooks
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Ensure directory roles exists
    file:
      path: roles
      state: directory

  - name: Ensure ansible-roles installed
    command: ansible-galaxy install -r requirements.yml --force
    changed_when: false

- import_playbook: pi-nodered.yml
- import_playbook: pi-jupyter.yml
- import_playbook: pi-databases.yml
