---
- name: Setup the pi for ansible playbooks
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Some output
      debug:
        verbosity: 1

- import_playbook: pi-nodered.yml
- import_playbook: pi-jupyter.yml
- import_playbook: pi-databases.yml
