---
- name: Romi chasis setup
  hosts: ubunturos
  connection: local
  vars:
    ros_user:
        name: pi-home 
        group: pi-home
    #ros_configuration: desktop-full
    ros_packages:
      - ros-base
      - urdf
      - tf
      - turtlebot3
      - gazebo-ros
  roles:
      - role: rarrais.ros
        become: yes


  tasks:
  - debug:
      var: ansible_user
      verbosity: 1
  - name: Install python packages
    become: yes
    apt:
      name:
        - python3
        - python3-smbus
        - python-smbus

...
