source 'https://rubygems.org'

gem 'capybara'
#gem "capybara", "~> 2.1.0.rc1"
gem "selenium-webdriver"
gem 'cucumber'
gem 'rspec'
#gem 'sinatra'
gem 'poltergeist'
gem 'rspec-expectations'
gem 'launchy'
gem 'rest-client'
